[tool]
[tool.poetry]
authors = ["Karan, email: first name at tensorparc .com"]
name = "root"
version = "0.0.0"
description="flask template"
[tool.poetry.dependencies]
flask = "==1.0.2"
python = "^3.8"
